In [1]:
using Pkg
Pkg.add(url="https://github.com/Jollywatt/GeometricAlgebra.jl", rev="v0.2.1")
Pkg.add("SymbolicUtils")
Pkg.add("Symbolics")

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.9/Project.toml`
  No Changes to `~/.julia/environments/v1.9/Manifest.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.9/Project.toml`
  No Changes to `~/.julia/environments/v1.9/Manifest.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.9/Project.toml`
  No Changes to `~/.julia/environments/v1.9/Manifest.toml`


In [9]:
Pkg.add("JSON")

   Resolving package versions...
    Updating `~/.julia/environments/v1.9/Project.toml`
  [682c06a0] + JSON v0.21.4
  No Changes to `~/.julia/environments/v1.9/Manifest.toml`


In [10]:
using GeometricAlgebra
using SymbolicUtils
using NPZ
using JSON

In [3]:
using GeometricAlgebra:
	bits_to_indices,
    componentindex
bits_to_indices(UInt64(4))

1-element Vector{Int64}:
 3

In [29]:
x = 4 * blades[4] + 2 * blades[2]

8-component Multivector{Cl"++0", 0:3, MVector{8, Int64}}:
 2 v1
 4 v12

In [39]:
simplify(inv(GeometricAlgebra.make_symbolic(Multivector{Cl"++0", 0:3 ,Vector{Float64}}, :kv)))

8-component Multivector{Cl"++0", 0:3, MVector{8, SymbolicUtils.BasicSymbolic{Real}}}:
 (kv[1]*(kv[1]^2 + kv[2]^2 + kv[3]^2 + kv[5]^2) + (-2kv[1]*kv[2] + 2kv[3]*kv[5])*kv[2] + (-2kv[1]*kv[3] - 2kv[2]*kv[5])*kv[3]) / (((kv[1]^2 + kv[2]^2 + kv[3]^2 + kv[5]^2)*kv[2] + kv[1]*(-2kv[1]*kv[2] + 2kv[3]*kv[5]) - (2kv[1]*kv[3] + 2kv[2]*kv[5])*kv[5])*kv[2] + ((kv[1]^2 + kv[2]^2 + kv[3]^2 + kv[5]^2)*kv[3] + kv[1]*(-2kv[1]*kv[3] - 2kv[2]*kv[5]) - (-2kv[1]*kv[2] + 2kv[3]*kv[5])*kv[5])*kv[3] - (-(kv[1]^2 + kv[2]^2 + kv[3]^2 + kv[5]^2)*kv[5] + (-2kv[1]*kv[2] + 2kv[3]*kv[5])*kv[3] + (2kv[1]*kv[3] + 2kv[2]*kv[5])*kv[2])*kv[5] + kv[1]*(kv[1]*(kv[1]^2 + kv[2]^2 + kv[3]^2 + kv[5]^2) + (-2kv[1]*kv[2] + 2kv[3]*kv[5])*kv[2] + (-2kv[1]*kv[3] - 2kv[2]*kv[5])*kv[3]))
 ((kv[1]^2 + kv[2]^2 + kv[3]^2 + kv[5]^2)*kv[2] + kv[1]*(-2kv[1]*kv[2] + 2kv[3]*kv[5]) - (2kv[1]*kv[3] + 2kv[2]*kv[5])*kv[5]) / (((kv[1]^2 + kv[2]^2 + kv[3]^2 + kv[5]^2)*kv[2] + kv[1]*(-2kv[1]*kv[2] + 2kv[3]*kv[5]) - (2kv[1]*kv[3] + 2kv[2]*kv[5])*kv[

In [33]:
GeometricAlgebra.inv(x)

8-component Multivector{Cl"++0", 0:3, StaticArraysCore.SizedVector{8, Float64, Vector{Float64}}}:
 -0.166667 v1
 -0.333333 v12

In [30]:
b2inv = GeometricAlgebra.reversion(x) / (GeometricAlgebra.reversion(x) * x)

8-component Multivector{Cl"++0", 0:3, MVector{8, Float64}}:
 0.722222 v1
 -0.777778 v12

In [35]:
x * inv(x)

8-component Multivector{Cl"++0", 0:3, MVector{8, Float64}}:
 1.0

In [4]:
f = zeros(Int64, 8, 8, 8)
blades = Array{Any}(undef, 8)
for i = 0:7
    blades[i+1] = BasisBlade{(1,1,0)}(1, UInt64(i))
end
for i = 1:8
    for j = 1:8
            f[i, j, (blades[i]*blades[j]).bits + 1] = (blades[i]*blades[j]).coeff
    end
end

In [47]:
f[1, 1, :]

8-element Vector{Int64}:
 1
 0
 0
 0
 0
 0
 0
 0

In [6]:
blade_indices = map(i -> bits_to_indices(blades[i].bits), 1:8)

8-element Vector{Vector{Int64}}:
 []
 [1]
 [2]
 [1, 2]
 [3]
 [1, 3]
 [2, 3]
 [1, 2, 3]

In [7]:
npzwrite("clifford_110_structure.npz", f)

In [11]:
json_data = JSON.json(blade_indices)
open("clifford_110_blades.json", "w") do f
    write(f, json_data)
end

42